#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @file can_frame.h
 * @brief Shared CAN frame and event types used by all CAN buses.
 *
 * Low-level TWAI and MCP2518FD frame types should be converted to these
 * types before frames are delivered to monitoring, logging, ISO-TP,
 * UDS, XCP, Web or USB services.
 */

#define CAN_FRAME_CLASSIC_DATA_MAX_LENGTH  (8U)
#define CAN_FRAME_FD_DATA_MAX_LENGTH       (64U)

#define CAN_FRAME_STANDARD_ID_MAX          (0x7FFU)
#define CAN_FRAME_EXTENDED_ID_MAX          (0x1FFFFFFFU)

#define CAN_EVENT_SEQUENCE_INITIAL         (1U)
#define CAN_TRANSACTION_ID_NONE            (0U)
#define CAN_NATIVE_SEQUENCE_NONE           (UINT32_MAX)

/**
 * @brief Logical CAN interface identifier.
 */
typedef enum
{
    /**
     * Primary Classical CAN interface using ESP32-S3 TWAI.
     */
    CAN_BUS_PRIMARY = 0,

    /**
     * Secondary Classical CAN/CAN FD interface using MCP2518FD.
     */
    CAN_BUS_SECONDARY,

    CAN_BUS_COUNT,

} can_bus_id_t;

/**
 * @brief Direction of a CAN frame.
 */
typedef enum
{
    CAN_FRAME_DIRECTION_RX = 0,
    CAN_FRAME_DIRECTION_TX,

} can_frame_direction_t;

/**
 * @brief Source of a frame timestamp.
 */
typedef enum
{
    /**
     * No valid timestamp is available.
     */
    CAN_TIMESTAMP_SOURCE_NONE = 0,

    /**
     * Timestamp was generated by ESP software.
     */
    CAN_TIMESTAMP_SOURCE_SOFTWARE,

    /**
     * Timestamp was generated by the CAN controller.
     */
    CAN_TIMESTAMP_SOURCE_HARDWARE,

} can_timestamp_source_t;

/**
 * @brief Shared CAN frame flags.
 */
typedef enum
{
    /**
     * Frame uses a 29-bit extended identifier.
     */
    CAN_FRAME_FLAG_EXTENDED_ID =
        (1UL << 0U),

    /**
     * Classical CAN Remote Transmission Request.
     */
    CAN_FRAME_FLAG_REMOTE =
        (1UL << 1U),

    /**
     * CAN FD frame.
     */
    CAN_FRAME_FLAG_FD =
        (1UL << 2U),

    /**
     * CAN FD Bit Rate Switch is enabled.
     */
    CAN_FRAME_FLAG_BRS =
        (1UL << 3U),

    /**
     * CAN FD Error State Indicator is set.
     */
    CAN_FRAME_FLAG_ESI =
        (1UL << 4U),

} can_frame_flags_t;


#define CAN_FRAME_FLAGS_MASK             \
    (                                    \
        CAN_FRAME_FLAG_EXTENDED_ID |     \
        CAN_FRAME_FLAG_REMOTE |          \
        CAN_FRAME_FLAG_FD |              \
        CAN_FRAME_FLAG_BRS |             \
        CAN_FRAME_FLAG_ESI               \
    )

/**
 * @brief Shared Classical CAN or CAN FD frame.
 */
typedef struct
{
    /**
     * Logical source or destination CAN interface.
     */
    can_bus_id_t bus;

    /**
     * 11-bit or 29-bit CAN identifier.
     */
    uint32_t identifier;

    /**
     * Combination of can_frame_flags_t values.
     */
    uint32_t flags;

    /**
     * Raw CAN DLC value from 0 to 15.
     *
     * Classical CAN DLC values from 0 to 8 represent the corresponding
     * payload length. Values from 9 to 15 still carry at most 8 bytes and
     * are preserved for monitoring and logging.
     *
     * CAN FD DLC values from 9 to 15 represent 12, 16, 20, 24, 32, 48
     * and 64 bytes.
     */
    uint8_t dlc;

    /**
     * Actual number of payload bytes transmitted on the CAN bus.
     *
     * For CAN FD this value must match the payload length represented by
     * dlc. Applications using a non-representable payload length must pad
     * data and set data_length to the encoded DLC length.
     *
     * Remote frames use zero because they do not carry payload data.
     */
    uint8_t data_length;

    /**
     * Frame payload.
     *
     * Remote frames do not contain payload bytes.
     */
    uint8_t data[
        CAN_FRAME_FD_DATA_MAX_LENGTH
    ];

    /**
     * Frame timestamp converted to microseconds.
     */
    uint64_t timestamp_us;

    /**
     * Origin of timestamp_us.
     */
    can_timestamp_source_t timestamp_source;

} can_frame_t;

/**
 * @brief CAN frame event type.
 */
typedef enum
{
    /**
     * A frame was received from a CAN bus.
     */
    CAN_EVENT_RX = 0,

    /**
     * A frame was accepted for asynchronous transmission.
     */
    CAN_EVENT_TX_QUEUED,

    /**
     * Transmission was confirmed successfully by the controller.
     */
    CAN_EVENT_TX_COMPLETED,

    /**
     * Transmission completed unsuccessfully.
     */
    CAN_EVENT_TX_FAILED,

    /**
     * Transmission was aborted before successful completion.
     */
    CAN_EVENT_TX_ABORTED,

    CAN_EVENT_TYPE_COUNT,

} can_event_type_t;

/**
 * @brief Shared frame event delivered by the CAN router.
 */
typedef struct
{
    /**
     * Event type.
     */
    can_event_type_t type;

    /**
     * Frame direction.
     */
    can_frame_direction_t direction;

    /**
     * Associated CAN frame.
     */
    can_frame_t frame;

    /**
     * Globally increasing event sequence assigned by the CAN router.
     *
     * This value can be used to detect dropped events in monitoring,
     * logging and streaming consumers. Sequence wraparound is allowed.
     */
    uint32_t event_sequence;

    /**
     * Transmission identifier assigned when a frame is submitted.
     *
     * TX_QUEUED, TX_COMPLETED, TX_FAILED and TX_ABORTED events for the
     * same transmission use the same non-zero value.
     * CAN_TRANSACTION_ID_NONE is used for received frames.
     */
    uint32_t transaction_id;

    /**
     * Driver-specific transmission sequence, or
     * CAN_NATIVE_SEQUENCE_NONE when unavailable.
     */
    uint32_t native_sequence;

    /**
     * Result associated with the event.
     *
     * RX, TX_QUEUED and successful TX_COMPLETED events normally use
     * ESP_OK. Failed or aborted events contain the relevant error.
     */
    esp_err_t result;

} can_event_t;

/**
 * @brief Convert a CAN DLC value to payload length.
 *
 * @param[in] dlc Raw CAN DLC from 0 to 15.
 * @param[in] fd True for CAN FD DLC interpretation.
 * @param[out] data_length Decoded payload length.
 *
 * @return ESP_OK on success, ESP_ERR_INVALID_ARG if data_length is
 * NULL or the DLC is invalid for the selected frame format.
 */
esp_err_t can_frame_dlc_to_length(
    uint8_t dlc,
    bool fd,
    uint8_t *data_length
);

/**
 * @brief Convert a payload length to the smallest matching CAN DLC.
 *
 * CAN FD payload lengths that are not directly representable are
 * rounded up to the next supported DLC size. The caller must pad the
 * remaining payload bytes before transmission.
 *
 * @param[in] data_length Requested payload length.
 * @param[in] fd True to use CAN FD DLC encoding.
 * @param[out] dlc Encoded DLC.
 * @param[out] encoded_length Payload length represented by the DLC.
 *
 * @return ESP_OK on success, ESP_ERR_INVALID_ARG if an output pointer
 * is NULL, or ESP_ERR_INVALID_SIZE if data_length exceeds the selected
 * CAN format capacity.
 */
esp_err_t can_frame_length_to_dlc(
    uint8_t data_length,
    bool fd,
    uint8_t *dlc,
    uint8_t *encoded_length
);

/**
 * @brief Validate a shared CAN frame.
 *
 * Validation includes bus identifier, CAN identifier width, supported
 * flag combinations, DLC, payload length and Classical CAN/CAN FD
 * restrictions.
 *
 * @param[in] frame Frame to validate.
 *
 * @return ESP_OK when valid, ESP_ERR_INVALID_ARG if frame is NULL or
 * contains an invalid field combination, or ESP_ERR_INVALID_SIZE for
 * an unsupported payload size.
 */
esp_err_t can_frame_validate(
    const can_frame_t *frame
);

#ifdef __cplusplus
}
#endif
